name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welkom bij SNS! fijn dat je aan de slag bent gegaan!'' first issue'
        pr-message: 'Welkom bij SNS! fijn dat je aan de slag bent gegaan!'' first pr'
